#!/bin/sh

# Available under the BSD3 license, which can be found in the
# LICENSE file in the same directory as this file.

res="`git grep --cached --color=always "git-forbid"`"

if [[ -z "${res// }" ]]
then
	exit 0
else
	echo "git-forbid messages found. "
	echo "-----------------------------"
	echo "$res"
	echo "-----------------------------"
    echo "Errors found, aborting commit. "
	echo "To fix this, edit and stage the files."
	echo "To ignore this error, use: git commit --no-verify"
    exit 1
fi

exit 0